//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonosCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefonos
    {
        public int PhoneID { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<int> ClienteID { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
